### ISSUE TITLE
Add option to avoid fade on borders

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#56]
As required by Ryan.

Currently the map degrade into ocean at the borders.

**Comment by psi29a** [comment]
This is great, as some of my heightmap generation techniques wrap around so that when used in a game for example... it is seamless.

**Comment by ftomassetti** [comment]
The various simulations wraps around but I had the fade effect anyway because I thought it was nicer/easier to have ocean at the borders (some users could not want to implement wrapping but add an infinite ocean at the borders, and think about all the maps you have seen: at the border there is always water, they never wrap in the middle of Asia).

Currently we translate the map to have as few land as possible at the borders and then apply the fade, maybe we can avoid the fade connecting it to an option (and we could even have it off by default)

**Comment by psi29a** [comment]
My way of handling that was also fading using a circular mask... not the best, but it worked. ;)

I like your way better and having an option is ideal.

**Comment by SourceRyan** [comment]
Having an ocean border is ideal when using the map standalone. However, when the resulting map and greyscale image is used with a tool like http://maptoglobe.bitbucket.org/, you will notice an island chain or continent that fades out in the middle, and continues on either side. 
Building off the Asia example, often you will find maps that have the Chukotka Peninsula in Russia wrapped around off of the American west coast. If you're using the map with world building, it's nice to have island chains and/or straits to model how populations migrated from one continent to another.

On a related note, having arctic/antarctic continents generate would be nice. Due to projection/distortion they would show up as strips of land along the polar borders of the map, but when applied to a globe, look fine. As of right now, the generated map results in thin stretched spikes of land towards the poles.
